name: Test


on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: "windows-latest"
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 15
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Update rubygems & bundler
      run: |
        ruby -v
        gem update --system
    - name: install dependencies
      run: |
        bin/setup
    - name: Compile extension
      run: |
        npm run build
        npm run package
    - name: Run minitest tests
      run: |
        xvfb-run -a node ./out/test/runMinitestTests.js
    - name: Run rspec tests
      run: |
        xvfb-run -a node ./out/test/runRspecTests.js
    - name: Run Ruby test
      run: |
        cd ruby && bundle exec rake
